#!/usr/bin/env python3
"""Emit hbm_probe_np<N>.cpp: the 32-port HBM probe with N ports (N a multiple of 8, <= 32).
Iter79 step 0b: the same reader structure, so a kernel assigned to another SLR
measures the shell's own SLR crossing for N masters."""
import sys
N = int(sys.argv[1]); assert N % 8 == 0 and 8 <= N <= 32
words = N // 8
L = []
L.append(f'/* GENERATED by gen_probe.py {N}: {N}-port variant of hbm_probe.cpp (Iter79 step 0b). */')
L.append('#include <ap_int.h>\n#include <hls_stream.h>\n#include <stdint.h>\ntypedef ap_uint<512> Beat512;')
L.append('#ifndef PROBE_READ_OUTSTANDING\n#define PROBE_READ_OUTSTANDING 4\n#endif')
L.append('#define PROBE_PRAGMA_(d) _Pragma(#d)\n#define PROBE_PRAGMA(d) PROBE_PRAGMA_(d)')
L.append('#define PROBE_READ_AXI(port_name, bundle_name) \\\n    PROBE_PRAGMA(HLS interface m_axi port=port_name offset=slave bundle=bundle_name \\\n                 max_widen_bitwidth=512 max_read_burst_length=64 \\\n                 num_read_outstanding=PROBE_READ_OUTSTANDING)')
L.append('''template <int PORT>
static void probe_reader(const Beat512 *w, uint32_t beats, uint32_t reps,
                         hls::stream<ap_uint<64> > &sum) {
#pragma HLS inline off
    ap_uint<64> acc = 0;
probe_rep: for (uint32_t r = 0; r < reps; ++r) {
#pragma HLS loop_tripcount min=1 max=8
    probe_beat: for (uint32_t i = 0; i < beats; ++i) {
#pragma HLS loop_tripcount min=1366528 max=1366528
#pragma HLS pipeline II=1
            const Beat512 v = w[i];
            acc ^= (ap_uint<64>)v.range(63, 0) ^ (ap_uint<64>)v.range(511, 448)
                   ^ (ap_uint<64>)i;
        }
    }
    sum.write(acc);
}''')
args = ', '.join(f'hls::stream<ap_uint<64> > &s{i}' for i in range(N))
L.append(f'static void probe_collect({args}, Beat512 *out) {{\n#pragma HLS inline off')
L.append('    ' + ' '.join(f'Beat512 w{j} = 0;' for j in range(words)))
for i in range(N):
    L.append(f'    w{i//8}.range(64 * {i%8} + 63, 64 * {i%8}) = s{i}.read();')
L.append('    ' + ' '.join(f'out[{j}] = w{j};' for j in range(words)) + '\n}')
pargs = ', '.join(f'const Beat512 *w{i}' for i in range(N))
L.append(f'extern "C" void hbm_probe(Beat512 *out, {pargs}, uint32_t beats, uint32_t reps) {{')
L.append('#pragma HLS interface m_axi port=out offset=slave bundle=mem0 max_widen_bitwidth=512 max_write_burst_length=16 num_write_outstanding=4')
for i in range(N):
    L.append(f'    PROBE_READ_AXI(w{i}, mem{i})')
L.append('#pragma HLS interface s_axilite port=beats\n#pragma HLS interface s_axilite port=reps\n#pragma HLS interface s_axilite port=return')
L.append('    hls::stream<ap_uint<64> > ' + ', '.join(f's{i}' for i in range(N)) + ';')
L.append('#pragma HLS dataflow')
for i in range(N):
    L.append(f'    probe_reader<{i}>(w{i}, beats, reps, s{i});')
L.append('    probe_collect(' + ', '.join(f's{i}' for i in range(N)) + ', out);\n}')
open(f'hbm_probe_np{N}.cpp', 'w').write('\n'.join(L) + '\n'); print(f'wrote hbm_probe_np{N}.cpp')
